version: "3.9"
services:
  backend:
    build: ./server
    ports: ["4000:4000"]
    environment:
      - JWT_SECRET=change_me
      - CLIENT_ORIGIN=http://localhost
  frontend:
    build: ./client
    ports: ["80:80"]
    environment:
      - VITE_API_URL=http://localhost:4000
