version: "3.9"
services:
  backend:
    build: ./server
    ports: ["8080:8080"]
    environment:
      - AWS_REGION=ap-southeast-2
      - CLIENT_ORIGINS=http://n11817143-videoapp.cab432.com
  frontend:
    build: ./client
    ports: ["80:80"]
    environment:
      - VITE_API_URL=http://n11817143-videoapp.cab432.com/api
